services:
 pgdatabase:
 # Configuration related to postgres db
  image: postgres:13
  environment:
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root 
     - POSTGRES_DB=ny_taxi_postgres_data
  volumes:
      # Specifying folder mapping and mode (read/write by default)
     - "./ny_taxi_postgres_data:/var/lib/postgres/data:rw"
  ports:
     - "5432:5432"
  networks:
     - pg-network
  
 pgadmin:
   # Configuration related to pgAdmin
  image: dpage/pgadmin4
  environment:
     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
  ports:
     - "8080:80"
  networks:
     - pg-network

networks:
  pg-network:
    name: pg-network
# We do not need to create a network as we defined them in docker compose file
# They automatically become a prt of same network

    
